### ISSUE TITLE
Herokuへのデプロイを試す

### ISSUE THREAD

**Issue by shg25** [shg25/rnsite#19]
プランはFreeで試す
https://jp.heroku.com/pricing#containers

Pythonのサポートページ
https://devcenter.heroku.com/ja/categories/python-support

Heroku Postgres
https://elements.heroku.com/addons/heroku-postgresql

MySQLと使うなら`ClearDB MySQL`っていうのを使うけど割高なので今回はパス
https://elements.heroku.com/addons/cleardb

可能なら環境変数の設定も調べる

**Comment by shg25** [comment]
Heroku公式のPythonサポートページの
https://devcenter.heroku.com/ja/categories/python-support

Heroku スターターガイド (Python)からやってみる
https://devcenter.heroku.com/ja/articles/getting-started-with-python

**Comment by shg25** [comment]
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-2

install the Heroku Command Line Interface (CLI)
```
$ brew install heroku/brew/heroku
```

エラー
>Error: Your Command Line Tools are too outdated.
>You should download the Command Line Tools for Xcode 12.5.

これやってから実行してもエラー
>Update them from Software Update in System Preferences or run:
>  softwareupdate --all --install --force

こっちやってから実行すると成功
>If that doesn't show you any updates, run:
>  sudo rm -rf /Library/Developer/CommandLineTools
>  sudo xcode-select --install

なんか書いてあるけどやったほうがいいのかな、とりあえずパス
>To use the Heroku CLI's autocomplete --
>  Via homebrew's shell completion:
>    1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
>        NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
>              and called, either explicitly or via a framework like oh-my-zsh.
>    2) Then run
>      $ heroku autocomplete --refresh-cache
>  OR
>  Use our standalone setup:
>    1) Run and follow the install steps:
>      $ heroku autocomplete

-v
>heroku/7.54.0 darwin-x64 node-v12.21.0

ログインもブラウザ起動して完了
```
$ heroku login
```

**Comment by shg25** [comment]
さっき出てたメッセージのやつ、インストールしとく

Heroku CLI のオートコンプリート
https://devcenter.heroku.com/ja/articles/heroku-cli-autocomplete

```
$ heroku autocomplete
```

>1) Add the autocomplete env var to your bash profile and source it
>$ printf "$(heroku autocomplete:script bash)" >> ~/.bashrc; source ~/.bashrc
>
>NOTE: If your terminal starts as a login shell you may need to print the init script into ~/.bash_profile or ~/.profile.
>
>2) Test it out, e.g.:
>$ heroku <TAB><TAB>                 # Command completion
>$ heroku apps:info --<TAB><TAB>     # Flag completion
>$ heroku apps:info --app=<TAB><TAB> # Flag option completion

こっちも実行しておく
```
$ printf "$(heroku autocomplete:script bash)" >> ~/.bashrc; source ~/.bashrc
```

**Comment by shg25** [comment]
スターターガイドに戻る

サンプルソースclone
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-3

アプリをデプロイする
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-4

アプリ作成
```
$ heroku create
```

コードをデプロイ
```
$ git push heroku main
```

アプリのインスタンスが 1 つ以上実行されていることを確認
```
$ heroku ps:scale web=1
```

Webサイトを開く
```
$ heroku open
```

**Comment by shg25** [comment]
ログを表示する
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-5

```
$ heroku logs --tail
```

`Control+C` で停止

**Comment by shg25** [comment]
Procfile を定義する
https://devcenter.heroku.com/ja/articles/getting-started-with-python#procfile

アプリのルートに `Procfile` を置いて、アプリ起動時に実行するコマンドを宣言する

```
web: gunicorn gettingstarted.wsgi
```
`web`というプロセスタイプに対して、HTTP ルーティング​スタックにアタッチしている

更に別のプロセスタイプを記述することもできる
例えば、アイテムをキューから外す処理を実行するバックグラウンドプロセスなど

あと、サンプルに置いてある `Procfile.windows` はWindows環境でローカル開発するためのもの

**Comment by shg25** [comment]
​アプリをスケールする
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-6

`dyno` の数を確認
```
$ heroku ps
```

`dyno` の数を0にする → エラーになる
```
$ heroku ps:scale web=0
```

`dyno` の数を1にする
```
$ heroku ps:scale web=1
$ heroku open
```

2以上にするにはアカウントの確認が必要
（クレジットカード追加など）
#23 で、そのうちやる

**Comment by shg25** [comment]
アプリの依存関係を宣言する
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-7

ルートディレクトリに `requirements.txt`​ を格納

デモアプリの例
```
django
gunicorn
django-heroku
```

デプロイするとHerokuはこのファイルを読み出して `pip install -r`​ コマンドを使用して適切な Python の依存関係をインストールする

ローカルで実行する
```
$ pip install -r requirements.txt
```
疑問：ローカルはpip3でやってるけどHerokuは問題なく実行できるのだろうか…

インストールされたパッケージの確認
```
$ pip list
```

**Comment by shg25** [comment]
​アプリをローカルで実行する
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-8

これは問題ないけど
```
python manage.py collectstatic
```

ここでエラー
```
$ heroku local web

[OKAY] Loaded ENV .env File as KEY=VALUE Format
22:57:28 web.1   |  /bin/sh: gunicorn: command not found
[DONE] Killing all processes with signal  SIGINT
22:57:28 web.1   Exited with exit code null
```

デモプロジェクトがDjango2で、今やってるDjango3と違うしパスしたい気もするし、`gunicorn: command not found` でエラーはよくあるみたいでDjango3でも問題起きるかも。

一旦、このまま進めて問題があれば検討する。

**Comment by shg25** [comment]
ローカルの変更をプッシュする
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-9

- パッケージの追加があれば`requirements.txt`に追記
- 必要に応じてソースを習性
- `git commit`
- `git push heroku main`でデプロイ
- `heroku open`で確認

**Comment by shg25** [comment]
アドオンをプロビジョニングする
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-10

Papertrailというアドオンをプロビジョニングする
```
$ heroku addons:create papertrail
```
アカウントの確認が必要なので後回しにしてた #23 をやった


アドオンを確認
```
heroku addons
```

プロビジョニングしたPapertrailを開く
```
heroku addons:open papertrail
```
ブラウザが開いてログが見れる

**Comment by shg25** [comment]
コンソールを起動する
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-11

​コンソールを起動する

[One-off dyno](https://devcenter.heroku.com/ja/articles/one-off-dynos)​で、`heroku run` コマンドを使ってコマンドを実行できる
```
$ heroku run python manage.py shell
```

```
>>> import requests
>>> print(requests.get('http://httpbin.org/status/418').text)

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
>>> exit()
```

別の`One-off dyno`を作成し、この`dyno`でシェルを開く`bash​`コマンドを実行
```
$ heroku run bash

Running `bash` attached to terminal... up, run.3052
~ $ ls
gettingstarted  hello  manage.py  Procfile  README.md  requirements.txt  runtime.txt  staticfiles
~ $ exit
exit
```

**Comment by shg25** [comment]
​環境設定を定義する
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-12

環境設定TIMESを取得して使う
```
import os

def index(request):
    times = int(os.environ.get('TIMES',3))
    return HttpResponse('Hello! ' * times)
```

`heroku local`では'.env'ファイルに記述した内容が読まれる
```
TIMES=2
```

Heroku側に設定する
```
$ heroku config:set TIMES=2
```

Heroku側の設定を確認する
```
$ heroku config
== sharp-rain-871 Config Vars
PAPERTRAIL_API_TOKEN: erdKhPeeeehIcdfY7ne
TIMES: 2
```

（これが環境変数的なやつ？）

**Comment by shg25** [comment]
データベースをプロビジョニングする
https://devcenter.heroku.com/ja/articles/getting-started-with-python#-13

Heroku Postgresは無料でアプリのデプロイ時に自動的にプロビジョニングされている

heroku-postgresqlがプロビジョニングされていることを確認する
```
$ heroku addons
```

DATABASE_URLを確認
```
$ heroku config
```

さらに詳細を表示する`pg`コマンド
```
$ heroku pg
```


Django の`manage.py migrate​`を実行
```
$ heroku run python manage.py migrate
```

リモートデータベースに接続
※ローカル環境にPostgresが入ってる前提
```
$ heroku pg:psql
```

**Comment by shg25** [comment]
Heroku のための Django アプリの設定
https://devcenter.heroku.com/ja/articles/django-app-configuration

これを元にrnsite用に設定を追加してみようと思ったけど、Django3で必要そうなファイルが微妙に違う気もするのでGithubで適当に探して見つけたソースも参考に

janProg / Django3-CRUD
https://github.com/janProg/Django3-CRUD

Procfile
```
web: gunicorn rnsite.wsgi
```

必要なパッケージのインストール
```
$ pip3 install gunicorn
$ pip3 install django-heroku
$ pip3 install whitenoise
```

requirements.txt
バージョン番号も指定できる模様
```
Django==3.1.3
django-heroku==0.3.1
gunicorn==20.1.0
pytz==2020.4
requests=2.25.0
whitenoise==5.2.0
```

settings.py の変更

```
$ pip install django-heroku
```

```
import django_heroku

# Activate Django-Heroku.
django_heroku.settings(locals())
```

**Comment by shg25** [comment]
比較としてデモアプリの正常なPUSHログ
```
$ git push heroku main
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 489 bytes | 489.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/python
remote: -----> Python app detected
remote: -----> Using Python version specified in runtime.txt
remote: -----> No change in requirements detected, installing from cache
remote: -----> Using cached install of python-3.9.5
remote: -----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote: -----> $ python manage.py collectstatic --noinput
remote:        129 static files copied to '/tmp/build_006986dc/staticfiles', 407 post-processed.
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 61.6M
remote: -----> Launching...
remote:        Released v12
remote:        https://glacial-wave-84161.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/glacial-wave-84161.git
   b15ebdf..2875b06  main -> main

```

**Comment by shg25** [comment]
pythonって認識しておらず。
デモアプリを見るとルートに`runtime.txt`があり`python-3.9.5`の記述。
これも入れるが、エラー。

そもそも'main'ブランチに何も入れてなかったのでマージしてpushしたら変化あり。
```
$ git push heroku main
Enumerating objects: 235, done.
Counting objects: 100% (235/235), done.
Delta compression using up to 8 threads
Compressing objects: 100% (214/214), done.
Writing objects: 100% (235/235), 184.34 KiB | 6.58 MiB/s, done.
Total 235 (delta 105), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Determining which buildpack to use for this app
remote: -----> Python app detected
remote: -----> Using Python version specified in runtime.txt
remote:  !     Python has released a security update! Please consider upgrading to python-3.9.5
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-3.9.4
remote: -----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        ERROR: Invalid requirement: 'requests=2.25.0' (from line 5 of /tmp/build_40c07537/requirements.txt)
remote:        Hint: = is not a valid operator. Did you mean == ?
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to pacific-mountain-93619.
remote: 
To https://git.heroku.com/pacific-mountain-93619.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/pacific-mountain-93619.git'
```

初歩すぎた。
そして次のエラーを考える。

**Comment by shg25** [comment]
`==`を`=`って書いてただけだったので修正 → #25
※Herokuが落ち着くまで`main`ブランチを直接編集して`develop`ブランチへ

そして次のエラー
```
5$ git push heroku main
Enumerating objects: 238, done.
Counting objects: 100% (238/238), done.
Delta compression using up to 8 threads
Compressing objects: 100% (217/217), done.
Writing objects: 100% (238/238), 184.52 KiB | 6.15 MiB/s, done.
Total 238 (delta 107), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Determining which buildpack to use for this app
remote: -----> Python app detected
remote: -----> Using Python version specified in runtime.txt
remote:  !     Python has released a security update! Please consider upgrading to python-3.9.5
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-3.9.4
remote: -----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting Django==3.1.3
remote:          Downloading Django-3.1.3-py3-none-any.whl (7.8 MB)
remote:        Collecting django-heroku==0.3.1
remote:          Downloading django_heroku-0.3.1-py2.py3-none-any.whl (6.2 kB)
remote:        Collecting gunicorn==20.1.0
remote:          Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
remote:        Collecting pytz==2020.4
remote:          Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
remote:        Collecting requests==2.25.0
remote:          Downloading requests-2.25.0-py2.py3-none-any.whl (61 kB)
remote:        Collecting whitenoise==5.2.0
remote:          Downloading whitenoise-5.2.0-py2.py3-none-any.whl (19 kB)
remote:        Collecting sqlparse>=0.2.2
remote:          Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
remote:        Collecting asgiref<4,>=3.2.10
remote:          Downloading asgiref-3.3.4-py3-none-any.whl (22 kB)
remote:        Collecting psycopg2
remote:          Downloading psycopg2-2.8.6.tar.gz (383 kB)
remote:        Collecting dj-database-url>=0.5.0
remote:          Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
remote:        Collecting idna<3,>=2.5
remote:          Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
remote:        Collecting urllib3<1.27,>=1.21.1
remote:          Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
remote:        Collecting chardet<4,>=3.0.2
remote:          Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
remote:        Collecting certifi>=2017.4.17
remote:          Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
remote:        Building wheels for collected packages: psycopg2
remote:          Building wheel for psycopg2 (setup.py): started
remote:          Building wheel for psycopg2 (setup.py): finished with status 'done'
remote:          Created wheel for psycopg2: filename=psycopg2-2.8.6-cp39-cp39-linux_x86_64.whl size=523854 sha256=3740ace0c7bbd2b5dd2238b78cb8e7ee235baa45bfcf13e05e5112e685e95538
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-1bb6ykt7/wheels/a2/07/10/a9a82e72d50feb8d646acde6a88000bbf2ca0f82e41aea438a
remote:        Successfully built psycopg2
remote:        Installing collected packages: sqlparse, pytz, asgiref, Django, psycopg2, dj-database-url, whitenoise, django-heroku, gunicorn, idna, urllib3, chardet, certifi, requests
remote:        Successfully installed Django-3.1.3 asgiref-3.3.4 certifi-2021.5.30 chardet-3.0.4 dj-database-url-0.5.0 django-heroku-0.3.1 gunicorn-20.1.0 idna-2.10 psycopg2-2.8.6 pytz-2020.4 requests-2.25.0 sqlparse-0.4.1 urllib3-1.26.5 whitenoise-5.2.0
remote: -----> $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "/tmp/build_097f5f85/manage.py", line 22, in <module>
remote:            main()
remote:          File "/tmp/build_097f5f85/manage.py", line 18, in main
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
remote:            django.setup()
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
remote:            apps.populate(settings.INSTALLED_APPS)
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
remote:            app_config = AppConfig.create(entry)
remote:          File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/config.py", line 90, in create
remote:            module = import_module(entry)
remote:          File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
remote:        ModuleNotFoundError: No module named 'widget_tweaks'
remote: 
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
remote: 
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote: 
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote: 
remote:        https://devcenter.heroku.com/articles/django-assets
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to pacific-mountain-93619.
remote: 
To https://git.heroku.com/pacific-mountain-93619.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/pacific-mountain-93619.git'
```

**Comment by shg25** [comment]
Djangoはデプロイ時にこのコマンドを実行
```
$ python manage.py collectstatic --noinput
```

このコマンドはローカルで実行してもエラーになり、エラーを回避するには、ルートに`static`フォルダと`staticfiles`フォルダが必要。

gitでディレクトリを活かすために、更にフォルダを作って'.gitkeep'を入れてみる。
https://stackoverflow.com/questions/62779416/ignoring-a-folder-inside-static-files-using-gitignore-in-a-django-project

しかしエラー。

すっきりしないけど、一度、メッセージにもある通り、以下のConfigを設定して、`python manage.py collectstatic --noinput`をパスする

```
$ heroku config:set DISABLE_COLLECTSTATIC=1
```

外す時はunset
```
$ heroku config:unset DISABLE_COLLECTSTATIC
```

するとデプロイが無事に完了。
すっきりしないので、改めて理解するために宿題にして、次をやる。

`heroku open`からサイトにアクセスするとエラー発生。
エラーメッセージの指示通りログを確認。
```
2021-06-13T16:49:44.912900+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pacific-mountain-93619.herokuapp.com request_id=1086e50e-4e8b-449e-81a4-39f807e1f760 fwd="221.251.84.69" dyno= connect= service= status=503 bytes= protocol=https
2021-06-13T16:49:45.260446+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=pacific-mountain-93619.herokuapp.com request_id=31234472-0d12-4022-90f1-8394a315ab01 fwd="221.251.84.69" dyno= connect= service= status=503 bytes= protocol=https
```

引き続き確認する

**Comment by shg25** [comment]
恐らく、
Heroku用の必要なファイルが足りないとか
そのファイルの記述が間違ってるとか

具体的にどこが問題か見つけられず。
別のローカルリポジトリ作って、Django3の初期状態でデプロイしてみるとよいのかな。
迷うところ。

**Comment by shg25** [comment]
このメッセージかも
>ModuleNotFoundError: No module named 'widget_tweaks'

https://base64.work/so/django/1436749
ということで、

ローカルでインストールして
>pip3 install django-widget-tweaks

`requirements.txt`に追記
>django-widget-tweaks==1.4.8

見たことあるDjangoのエラー画面が表示された！

>ProgrammingError at /
>relation "airs_air" does not exist
>LINE 1: ...d", "airs_air"."started", "airs_air"."ended" FROM "airs_air"...

**Comment by shg25** [comment]
makemigrationsで解決！
```
$ heroku run python manage.py makemigrations
$ heroku run python manage.py migrate
```

**Comment by shg25** [comment]
色々とイジったから心配になって、ローカルサーバ起動しなおしたけど、問題なさそう。
```
$ python3 manage.py runserver
```

**Comment by shg25** [comment]
[#issuecomment-860240354](#issuecomment-860240354) で後回しにしていた`DISABLE_COLLECTSTATIC`の問題が #98 で解消される
